import 'dotenv/config';
import express from 'express';
import cookieParser from 'cookie-parser';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { createClient } from '@supabase/supabase-js';

const app = express();
const port = Number(process.env.PORT || 3001);
const production = process.env.NODE_ENV === 'production';
const missingConfig=['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','SESSION_SECRET'].filter(key=>!process.env[key]);
if(missingConfig.length) throw new Error(`ConfiguraÃ§Ã£o ausente no arquivo .env: ${missingConfig.join(', ')}`);
const db = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth:{persistSession:false,autoRefreshToken:false} });
app.disable('x-powered-by'); app.set('trust proxy',1); app.use(express.json({limit:'100kb'})); app.use(cookieParser());

const attempts=new Map();
const limitLogin=(req,res,next)=>{const key=req.ip,now=Date.now(),item=attempts.get(key)||{count:0,reset:now+900000};if(now>item.reset){item.count=0;item.reset=now+900000}if(item.count>=10)return res.status(429).json({message:'Muitas tentativas. Aguarde alguns minutos.'});item.count++;attempts.set(key,item);next()};
const cookie='aflora_session';
const setupCookie='aflora_setup';
const cookieOptions={httpOnly:true,secure:production,sameSite:'strict',path:'/'};
const startSession=(res,user)=>{const token=jwt.sign({sub:user.id,username:user.username,role:user.role},process.env.SESSION_SECRET,{expiresIn:'8h',issuer:'aflora-api'});res.cookie(cookie,token,{...cookieOptions,maxAge:28800000})};
const auth=(req,res,next)=>{try{req.user=jwt.verify(req.cookies[cookie],process.env.SESSION_SECRET);next()}catch{res.status(401).json({message:'SessÃ£o expirada. Entre novamente.'})}};
const admin=(req,res,next)=>['admin','developer'].includes(req.user.role)?next():res.status(403).json({message:'Acesso exclusivo da administraÃ§Ã£o.'});
const auditOwner=(req,res,next)=>req.user.username==='victor.nogueira'?next():res.status(403).json({message:'Acesso Ã  auditoria nÃ£o autorizado.'});
const fail=(res,error)=>{console.error(error);if(error?.code==='PGRST204'&&/product_type|flavor/.test(error?.message||''))return res.status(503).json({message:'O cadastro de sabores ainda não foi habilitado no banco de dados.'});if(error?.code==='PGRST205')return res.status(503).json({message:'A tabela necessária ainda não existe no banco de dados.'});if(error?.code==='23514')return res.status(409).json({message:'O banco rejeitou um dos valores enviados. Atualize as constraints do banco.'});if(error?.code==='23505')return res.status(409).json({message:'Já existe um registro com este identificador.'});if(/fetch failed/i.test(error?.message||error?.details||''))return res.status(503).json({message:'Não foi possível acessar o banco de dados.'});res.status(500).json({message:`Não foi possível concluir a operação${error?.code?` (código ${error.code})`:''}.`})};

const auditAction={POST:'create',PUT:'update',PATCH:'update',DELETE:'delete'};
const paymentMethods=new Set(['Pix','Dinheiro','Cartão']);
app.use('/api',(req,res,next)=>{res.on('finish',()=>{const action=auditAction[req.method];if(!action||res.statusCode>=400||!req.user||req.path.startsWith('/auth'))return;const parts=req.path.split('/').filter(Boolean);if(parts[0]==='api')parts.shift();const entityType=parts[0],entityId=parts[1]||req.body?.id||null;const safeDetails={};for(const [key,value] of Object.entries(req.body||{})){if(!['password','password_hash','token'].includes(key))safeDetails[key]=value}db.from('audit_logs').insert({actor_id:req.user.sub,actor_username:req.user.username,action,entity_type:entityType,entity_id:String(entityId||''),details:safeDetails,ip_address:req.ip}).then(({error})=>{if(error&&error.code!=='PGRST205')console.error('Falha ao registrar auditoria:',error)})});next()});

app.get('/api/health',(_req,res)=>res.json({ok:true}));
app.post('/api/auth/login',limitLogin,async(req,res)=>{try{const username=String(req.body?.username||'').trim().toLowerCase(),password=String(req.body?.password||'');if(!username)return res.status(400).json({message:'Informe o usuÃ¡rio.'});const {data:user,error}=await db.from('app_users').select('id,username,password_hash,role,active').eq('username',username).maybeSingle();if(error)throw error;if(!user?.active)return res.status(401).json({message:'UsuÃ¡rio ou senha incorretos.'});if(!user.password_hash||user.password_hash==='FIRST_ACCESS'){const token=jwt.sign({sub:user.id,purpose:'password_setup'},process.env.SESSION_SECRET,{expiresIn:'15m',issuer:'aflora-api'});res.cookie(setupCookie,token,{...cookieOptions,maxAge:900000});attempts.delete(req.ip);return res.json({setupRequired:true,username:user.username})}if(!password||!await bcrypt.compare(password,user.password_hash))return res.status(401).json({message:'UsuÃ¡rio ou senha incorretos.'});startSession(res,user);attempts.delete(req.ip);res.json({user:{username:user.username,role:user.role}})}catch(e){fail(res,e)}});
app.post('/api/auth/set-password',async(req,res)=>{try{let claim;try{claim=jwt.verify(req.cookies[setupCookie],process.env.SESSION_SECRET)}catch{return res.status(401).json({message:'O prazo do primeiro acesso expirou. Entre novamente.'})}if(claim.purpose!=='password_setup')return res.status(401).json({message:'SolicitaÃ§Ã£o invÃ¡lida.'});const password=String(req.body?.password||'');if(password.length<8)return res.status(400).json({message:'A senha deve ter pelo menos 8 caracteres.'});const password_hash=await bcrypt.hash(password,12);const {data:user,error}=await db.from('app_users').update({password_hash}).eq('id',claim.sub).select('id,username,role').single();if(error)throw error;res.clearCookie(setupCookie,cookieOptions);startSession(res,user);res.json({user:{username:user.username,role:user.role}})}catch(e){fail(res,e)}});
app.post('/api/auth/logout',(_req,res)=>{res.clearCookie(cookie,cookieOptions);res.clearCookie(setupCookie,cookieOptions);res.status(204).end()});
app.get('/api/auth/session',auth,(req,res)=>res.json({user:{username:req.user.username,role:req.user.role}}));

const product=p=>({id:p.id,name:p.name,category:p.category,sku:p.sku,unit:p.unit,price:Number(p.price),cost:Number(p.cost||0),stock:Number(p.stock),minStock:Number(p.min_stock),active:p.active});
const sale=s=>({id:s.id,createdAt:s.created_at,items:s.items,total:Number(s.total),payment:s.payment==='CartÃ£o'?'Cartão':s.payment});
const batch=b=>({id:b.id,kind:b.product_type||'acai',flavor:b.flavor||'Tradicional',liters:Number(b.liters),openedAt:b.opened_at,endedAt:b.ended_at||undefined,cost:Number(b.cost),status:b.status});
const cost=c=>({id:c.id,description:c.description,category:c.category,amount:Number(c.amount),date:c.cost_date,paymentDate:c.payment_date||c.cost_date,paidBy:c.paid_by||undefined,recurring:c.recurring,paid:Boolean(c.paid),paidAt:c.paid_at||undefined,notes:c.notes||undefined,installmentNumber:Number(c.installment_number||1),installmentsTotal:Number(c.installments_total||1),installmentGroupId:c.installment_group_id||undefined});
const material=m=>({id:m.id,name:m.name,categoryId:m.category_id,unit:m.unit,stock:Number(m.stock),minStock:Number(m.min_stock),cost:Number(m.cost||0),active:m.active,portionEnabled:Boolean(m.portion_enabled),portionQuantity:Number(m.portion_quantity||0)});
app.get('/api/store',auth,async(req,res)=>{try{const fields=req.user.role!=='employee'?'*':'id,name,category,sku,unit,price,stock,min_stock,active';const q=[db.from('products').select(fields).order('name')];if(req.user.role!=='employee')q.push(db.from('sales').select('*').order('created_at',{ascending:false}),db.from('acai_batches').select('*').order('opened_at',{ascending:false}));const out=await Promise.all(q);if(out.some(x=>x.error))throw out.find(x=>x.error).error;let costs=[],materials=[],materialCategories=[];const inventory=await Promise.all([db.from('materials').select('*').order('name'),db.from('material_categories').select('*').order('name')]);if(!inventory[0].error){materials=(inventory[0].data||[]).map(material)}if(!inventory[1].error){materialCategories=inventory[1].data||[]}if(req.user.role!=='employee'){const result=await db.from('costs').select('*').order('cost_date',{ascending:false});if(result.error&&result.error.code!=='PGRST205')throw result.error;costs=(result.data||[]).map(cost)}res.json({products:(out[0].data||[]).map(product),sales:req.user.role!=='employee'?(out[1].data||[]).map(sale):[],batches:req.user.role!=='employee'?(out[2].data||[]).map(batch):[],costs,materials,materialCategories})}catch(e){fail(res,e)}});
app.post('/api/sales',auth,async(req,res)=>{try{const s=req.body;if(!s?.id||!Array.isArray(s.items)||!s.items.length||!paymentMethods.has(s.payment))return res.status(400).json({message:'Venda inválida.'});const total=s.items.reduce((n,i)=>n+Number(i.quantity)*Number(i.unitPrice),0);if(total<=0)return res.status(400).json({message:'O total deve ser maior que zero.'});for(const i of s.items.filter(i=>i.kind==='product')){const {data:recipe,error:recipeError}=await db.from('recipe_items').select('material_id,quantity,materials(name,stock)').eq('product_id',i.productId);if(recipeError&&recipeError.code!=='PGRST205')throw recipeError;i.materialUsage=[];for(const r of recipe||[]){const needed=Number(r.quantity)*Number(i.quantity),available=Number(r.materials?.stock||0);if(available<needed)return res.status(409).json({message:`Material insuficiente: ${r.materials?.name||'item da receita'}.`});const update=await db.from('materials').update({stock:available-needed}).eq('id',r.material_id);if(update.error)throw update.error;i.materialUsage.push({materialId:r.material_id,name:r.materials?.name,quantity:needed})}}const row={id:s.id,created_at:new Date().toISOString(),items:s.items,total,payment:s.payment};let result=await db.from('sales').insert(row);if(result.error?.code==='23514'&&s.payment==='Cartão')result=await db.from('sales').insert({...row,payment:'CartÃ£o'});if(result.error)throw result.error;res.status(201).json({ok:true})}catch(e){fail(res,e)}});
app.patch('/api/sales/:id',auth,admin,async(req,res)=>{try{if(!paymentMethods.has(req.body.payment))return res.status(400).json({message:'Forma de pagamento inválida.'});const {error}=await db.from('sales').update({payment:req.body.payment}).eq('id',req.params.id);if(error)throw error;res.status(204).end()}catch(e){fail(res,e)}});
app.delete('/api/sales/:id',auth,admin,async(req,res)=>{try{const {data:sale,error}=await db.from('sales').select('items').eq('id',req.params.id).single();if(error)throw error;for(const item of (sale.items||[])){for(const usage of item.materialUsage||[]){const {data:m}=await db.from('materials').select('stock').eq('id',usage.materialId).single();if(m)await db.from('materials').update({stock:Number(m.stock)+Number(usage.quantity)}).eq('id',usage.materialId)}}const result=await db.from('sales').delete().eq('id',req.params.id);if(result.error)throw result.error;res.status(204).end()}catch(e){fail(res,e)}});
app.post('/api/products',auth,admin,async(req,res)=>{try{const p=req.body;const r=await db.from('products').insert({id:p.id,name:p.name,category:p.category,sku:p.sku,unit:p.unit,price:p.price,cost:p.cost,stock:p.stock,min_stock:p.minStock,active:true});if(r.error)throw r.error;if(Array.isArray(p.recipe)&&p.recipe.length){const recipeResult=await db.from('recipe_items').insert(p.recipe.map(i=>({product_id:p.id,material_id:i.materialId,quantity:Number(i.quantity)})));if(recipeResult.error)throw recipeResult.error}res.status(201).json({ok:true})}catch(e){fail(res,e)}});
app.put('/api/products/:id',auth,admin,async(req,res)=>{try{const p=req.body,r=await db.from('products').update({name:p.name,category:p.category,sku:p.sku,unit:p.unit,price:p.price,cost:p.cost,min_stock:p.minStock,active:p.active}).eq('id',req.params.id);if(r.error)throw r.error;res.status(204).end()}catch(e){fail(res,e)}});
app.delete('/api/products/:id',auth,admin,async(req,res)=>{try{const r=await db.from('products').delete().eq('id',req.params.id);if(r.error?.code==='23503')return res.status(409).json({message:'Este produto possui vendas vinculadas e nÃ£o pode ser excluÃ­do.'});if(r.error)throw r.error;res.status(204).end()}catch(e){fail(res,e)}});
app.patch('/api/products/:id/stock',auth,admin,async(req,res)=>{try{const {data:p,error}=await db.from('products').select('stock').eq('id',req.params.id).single();if(error)throw error;const stock=Math.max(0,Number(p.stock)+Number(req.body.delta||0)),r=await db.from('products').update({stock}).eq('id',req.params.id);if(r.error)throw r.error;res.json({stock})}catch(e){fail(res,e)}});
app.post('/api/material-categories',auth,admin,async(req,res)=>{try{const name=String(req.body.name||'').trim();if(!name)return res.status(400).json({message:'Informe o nome da categoria.'});const r=await db.from('material_categories').insert({id:req.body.id,name});if(r.error?.code==='23505')return res.status(409).json({message:'Esta categoria jÃ¡ existe.'});if(r.error)throw r.error;res.status(201).json({ok:true})}catch(e){fail(res,e)}});
app.delete('/api/material-categories/:id',auth,admin,async(req,res)=>{try{const r=await db.from('material_categories').delete().eq('id',req.params.id);if(r.error?.code==='23503')return res.status(409).json({message:'A categoria possui materiais e nÃ£o pode ser excluÃ­da.'});if(r.error)throw r.error;res.status(204).end()}catch(e){fail(res,e)}});
app.post('/api/materials',auth,admin,async(req,res)=>{try{const m=req.body,portionEnabled=Boolean(m.portionEnabled),portionQuantity=Number(m.portionQuantity||0);if(portionEnabled&&portionQuantity<=0)return res.status(400).json({message:'Informe uma quantidade vÃ¡lida para a porÃ§Ã£o padrÃ£o.'});const r=await db.from('materials').insert({id:m.id,name:m.name,category_id:m.categoryId,unit:m.unit,stock:m.stock,min_stock:m.minStock,cost:m.cost,active:true,portion_enabled:portionEnabled,portion_quantity:portionEnabled?portionQuantity:0});if(r.error)throw r.error;res.status(201).json({ok:true})}catch(e){fail(res,e)}});
app.put('/api/materials/:id',auth,admin,async(req,res)=>{try{const m=req.body,portionEnabled=Boolean(m.portionEnabled),portionQuantity=Number(m.portionQuantity||0);if(portionEnabled&&portionQuantity<=0)return res.status(400).json({message:'Informe uma quantidade vÃ¡lida para a porÃ§Ã£o padrÃ£o.'});const r=await db.from('materials').update({name:m.name,category_id:m.categoryId,unit:m.unit,min_stock:m.minStock,cost:m.cost,active:m.active,portion_enabled:portionEnabled,portion_quantity:portionEnabled?portionQuantity:0}).eq('id',req.params.id);if(r.error)throw r.error;res.status(204).end()}catch(e){fail(res,e)}});
app.patch('/api/materials/:id/stock',auth,admin,async(req,res)=>{try{const {data:m,error}=await db.from('materials').select('stock,portion_enabled,portion_quantity').eq('id',req.params.id).single();if(error)throw error;let delta;if(req.body.mode==='portions'){const portions=Number(req.body.quantity);if(!m.portion_enabled||Number(m.portion_quantity)<=0)return res.status(400).json({message:'Este material nÃ£o possui uma porÃ§Ã£o padrÃ£o configurada.'});if(!Number.isFinite(portions)||portions<=0)return res.status(400).json({message:'Informe uma quantidade vÃ¡lida de porÃ§Ãµes.'});delta=portions*Number(m.portion_quantity)}else if(req.body.mode==='units'){const quantity=Number(req.body.quantity);if(!Number.isFinite(quantity)||quantity<=0)return res.status(400).json({message:'Informe uma quantidade vÃ¡lida para a entrada.'});delta=quantity}else delta=Number(req.body.delta||0);const stock=Math.max(0,Number(m.stock)+delta),r=await db.from('materials').update({stock}).eq('id',req.params.id);if(r.error)throw r.error;res.json({stock,added:delta,portionsAdded:req.body.mode==='portions'?Number(req.body.quantity):null})}catch(e){fail(res,e)}});
app.delete('/api/materials/:id',auth,admin,async(req,res)=>{try{const r=await db.from('materials').delete().eq('id',req.params.id);if(r.error?.code==='23503')return res.status(409).json({message:'Este material faz parte de uma receita e nÃ£o pode ser excluÃ­do.'});if(r.error)throw r.error;res.status(204).end()}catch(e){fail(res,e)}});
app.post('/api/batches',auth,admin,async(req,res)=>{try{const b=req.body,kind=b.kind==='sorvete'?'sorvete':'acai',flavor=String(b.flavor||'').trim();if(!flavor)return res.status(400).json({message:'Informe o sabor do lote.'});const r=await db.from('acai_batches').insert({id:b.id,product_type:kind,flavor,liters:b.liters,cost:b.cost,opened_at:new Date().toISOString(),status:'open'});if(r.error)throw r.error;res.status(201).json({ok:true})}catch(e){fail(res,e)}});
app.patch('/api/batches/:id/close',auth,admin,async(req,res)=>{try{const r=await db.from('acai_batches').update({status:'closed',ended_at:new Date().toISOString()}).eq('id',req.params.id);if(r.error)throw r.error;res.json({ok:true})}catch(e){fail(res,e)}});
app.delete('/api/batches/:id',auth,admin,async(req,res)=>{try{const r=await db.from('acai_batches').delete().eq('id',req.params.id);if(r.error)throw r.error;res.status(204).end()}catch(e){fail(res,e)}});
const costRow=c=>({id:c.id,description:String(c.description||'').trim(),category:c.category,amount:Number(c.amount),cost_date:c.date,payment_date:c.paymentDate,paid_by:String(c.paidBy||'').trim()||null,recurring:Boolean(c.recurring),paid:Boolean(c.paid),paid_at:c.paidAt||null,notes:c.notes||null,installment_number:Number(c.installmentNumber||1),installments_total:Number(c.installmentsTotal||1),installment_group_id:c.installmentGroupId||null});
const validCost=c=>c.id&&c.description&&['Estoque','MÃ£o de obra','ConstruÃ§Ã£o','Aluguel','Energia','Marketing','Impostos','Outros'].includes(c.category)&&Number.isFinite(Number(c.amount))&&Number(c.amount)>=0&&/^\d{4}-\d{2}-\d{2}$/.test(c.date)&&/^\d{4}-\d{2}-\d{2}$/.test(c.paymentDate);
const addMonths=(value,months)=>{const [year,month,day]=value.split('-').map(Number),target=new Date(Date.UTC(year,month-1+months,1)),last=new Date(Date.UTC(target.getUTCFullYear(),target.getUTCMonth()+1,0)).getUTCDate();return `${target.getUTCFullYear()}-${String(target.getUTCMonth()+1).padStart(2,'0')}-${String(Math.min(day,last)).padStart(2,'0')}`};
const expandInstallments=c=>{const total=Math.min(120,Math.max(1,Number(c.installments)||1)),groupId=total>1?c.id:null;return Array.from({length:total},(_,index)=>({...c,id:total>1?`${c.id}-p${index+1}`:c.id,paymentDate:addMonths(c.paymentDate,index),installmentNumber:index+1,installmentsTotal:total,installmentGroupId:groupId}))};
app.post('/api/costs',auth,admin,async(req,res)=>{try{if(!validCost(req.body))return res.status(400).json({message:'Dados do custo invÃ¡lidos.'});const costs=expandInstallments(req.body),r=await db.from('costs').insert(costs.map(costRow)).select('*');if(r.error)throw r.error;res.status(201).json({costs:(r.data||[]).map(cost)})}catch(e){fail(res,e)}});
app.put('/api/costs/:id',auth,admin,async(req,res)=>{try{if(!validCost(req.body))return res.status(400).json({message:'Dados do custo invÃ¡lidos.'});const row=costRow(req.body);delete row.id;const r=await db.from('costs').update(row).eq('id',req.params.id);if(r.error)throw r.error;res.status(204).end()}catch(e){fail(res,e)}});
app.patch('/api/costs/:id/paid',auth,admin,async(req,res)=>{try{const paid=Boolean(req.body.paid),r=await db.from('costs').update({paid,paid_at:paid?new Date().toISOString():null}).eq('id',req.params.id);if(r.error)throw r.error;res.status(204).end()}catch(e){fail(res,e)}});
app.delete('/api/costs/:id',auth,admin,async(req,res)=>{try{const r=await db.from('costs').delete().eq('id',req.params.id);if(r.error)throw r.error;res.status(204).end()}catch(e){fail(res,e)}});
app.post('/api/costs/import',auth,admin,async(req,res)=>{try{const costs=req.body?.costs;if(!Array.isArray(costs)||!costs.length||costs.length>1000)return res.status(400).json({message:'A planilha deve conter entre 1 e 1.000 custos.'});if(costs.some(c=>!validCost(c)))return res.status(400).json({message:'Existem linhas invÃ¡lidas na planilha.'});const r=await db.from('costs').insert(costs.map(costRow));if(r.error)throw r.error;res.status(201).json({count:costs.length})}catch(e){fail(res,e)}});
const publicUser=u=>({id:u.id,username:u.username,role:u.role,active:u.active,needsPassword:!u.password_hash||u.password_hash==='FIRST_ACCESS',createdAt:u.created_at});
app.get('/api/users',auth,admin,async(_req,res)=>{try{const {data,error}=await db.from('app_users').select('id,username,role,active,password_hash,created_at').order('created_at');if(error)throw error;res.json({users:(data||[]).map(publicUser)})}catch(e){fail(res,e)}});
app.get('/api/audit-logs',auth,auditOwner,async(req,res)=>{try{const limit=Math.min(200,Math.max(1,Number(req.query.limit)||100));const {data,error}=await db.from('audit_logs').select('id,actor_username,action,entity_type,entity_id,details,created_at').order('created_at',{ascending:false}).limit(limit);if(error?.code==='PGRST205')return res.json({logs:[]});if(error)throw error;res.json({logs:data||[]})}catch(e){fail(res,e)}});
app.post('/api/users',auth,admin,async(req,res)=>{try{const username=String(req.body?.username||'').trim().toLowerCase(),role=req.body?.role;if(!/^[a-z0-9._-]{3,32}$/.test(username))return res.status(400).json({message:'Use de 3 a 32 caracteres: letras minÃºsculas, nÃºmeros, ponto, hÃ­fen ou sublinhado.'});if(!['admin','employee'].includes(role))return res.status(400).json({message:'Cargo invÃ¡lido.'});const {data,error}=await db.from('app_users').insert({username,role,password_hash:'FIRST_ACCESS',active:true}).select('id,username,role,active,password_hash,created_at').single();if(error?.code==='23505')return res.status(409).json({message:'Este nome de usuÃ¡rio jÃ¡ existe.'});if(error)throw error;res.status(201).json({user:publicUser(data)})}catch(e){fail(res,e)}});
app.patch('/api/users/:id/active',auth,admin,async(req,res)=>{try{if(req.params.id===req.user.sub)return res.status(400).json({message:'VocÃª nÃ£o pode desativar seu prÃ³prio usuÃ¡rio.'});const {data:target,error:targetError}=await db.from('app_users').select('role').eq('id',req.params.id).single();if(targetError)throw targetError;if(req.user.role==='admin'&&target.role!=='employee')return res.status(403).json({message:'Administradores sÃ³ podem gerenciar perfis de funcionÃ¡rios.'});const {error}=await db.from('app_users').update({active:Boolean(req.body.active)}).eq('id',req.params.id);if(error)throw error;res.status(204).end()}catch(e){fail(res,e)}});
app.put('/api/users/:id',auth,admin,async(req,res)=>{try{if(req.params.id===req.user.sub)return res.status(400).json({message:'VocÃª nÃ£o pode alterar seu prÃ³prio perfil.'});const {data:target,error:targetError}=await db.from('app_users').select('role').eq('id',req.params.id).single();if(targetError)throw targetError;if(req.user.role==='admin'&&target.role!=='employee')return res.status(403).json({message:'Administradores sÃ³ podem gerenciar perfis de funcionÃ¡rios.'});const username=String(req.body.username||'').trim().toLowerCase(),role=req.body.role;if(!/^[a-z0-9._-]{3,32}$/.test(username)||!['admin','employee'].includes(role))return res.status(400).json({message:'Dados do usuÃ¡rio invÃ¡lidos.'});const r=await db.from('app_users').update({username,role}).eq('id',req.params.id);if(r.error?.code==='23505')return res.status(409).json({message:'Este nome de usuÃ¡rio jÃ¡ existe.'});if(r.error)throw r.error;res.status(204).end()}catch(e){fail(res,e)}});
app.delete('/api/users/:id',auth,admin,async(req,res)=>{try{if(req.params.id===req.user.sub)return res.status(400).json({message:'VocÃª nÃ£o pode excluir seu prÃ³prio usuÃ¡rio.'});const {data:target,error:targetError}=await db.from('app_users').select('role').eq('id',req.params.id).single();if(targetError)throw targetError;if(req.user.role==='admin'&&target.role!=='employee')return res.status(403).json({message:'Administradores sÃ³ podem excluir perfis de funcionÃ¡rios.'});const r=await db.from('app_users').delete().eq('id',req.params.id);if(r.error)throw r.error;res.status(204).end()}catch(e){fail(res,e)}});

async function ensureUser(username,password,role){if(!username||!password)return;username=username.trim().toLowerCase();const password_hash=await bcrypt.hash(password,12);const {data,error}=await db.from('app_users').select('id').eq('username',username).maybeSingle();if(error)throw error;const result=data?await db.from('app_users').update({password_hash,role,active:true}).eq('id',data.id):await db.from('app_users').insert({username,password_hash,role,active:true});if(result.error)throw result.error}
async function bootstrap(){const username=String(process.env.ADMIN_USERNAME||'').trim().toLowerCase();await ensureUser(process.env.ADMIN_USERNAME,process.env.ADMIN_PASSWORD,username==='victor.nogueira'?'developer':'admin')}

export default app;

if(process.argv[1]&&import.meta.url===new URL(`file:///${process.argv[1].replace(/\\/g,'/')}`).href){
  const server=app.listen(port,'127.0.0.1',()=>{
    console.log(`Aflora API na porta ${port}`);
    bootstrap().catch(e=>console.error('Falha ao sincronizar o usuário administrador inicial:',e));
  });
  await new Promise((resolve,reject)=>{
    server.once('close',resolve);
    server.once('error',reject);
  });
}
